import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="flex flex-col justify-between min-h-screen w-full bg-dirtywhite">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="m-0 p-0 flex-1 flex justify-center items-center">
        <div>
          <h1 className="text-5xl font-bold text-center font-barlow">Next.js + TailwindCSS</h1>
          <div className="grid grid-cols-5 gap-6 max-w-3xl mx-auto mt-16">
            <div className="h-[50px] w-[50px] bg-hotpink"></div>
            <div className="h-[50px] w-[50px] bg-purple"></div>
            <div className="h-[50px] w-[50px] bg-midpurple"></div>
            <div className="h-[50px] w-[50px] bg-lightpurple"></div>
            <div className="h-[50px] w-[50px] bg-blue"></div>
            <div className="h-[50px] w-[50px] bg-bluegray"></div>
            <div className="h-[50px] w-[50px] bg-white"></div>
            <div className="h-[50px] w-[50px] bg-black"></div>
            <div className="h-[50px] w-[50px] bg-yellow"></div>
            <div className="h-[50px] w-[50px] bg-green"></div>
          </div>
        </div>
      </main>

      <footer className="m-0 p-8 flex justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="h-[1em] ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
